### ISSUE TITLE
can not drive the st7789 screen

### ISSUE THREAD

**Issue by heixiaoma** [russhughes/lv_st7789#10]
Hello, I use the following parameters and can not drive the st7789 screen. My chip is esp32-recover-b 8MB PSRAM 16MB flash
```
from ili9XXX import st7789
import espidf as esp
disp = st7789(mosi=19, clk=21, dc=22, rst=18,backlight=23, spihost=esp.VSPI_HOST,  width=240, height=240)
```

**Comment by russhughes** [comment]
This driver is no longer supported, the LVGL driver in https://github.com/lvgl/lv_binding_micropython should be used.
