### ISSUE TITLE
More fonts

### ISSUE THREAD

**Issue by jdtsmith** [russhughes/lv_st7789#2]
It would be wonderful to enable more fonts in `lib/lv_bindings/lv_conf.h`, e.g.:

```c
/*Montserrat fonts with ASCII range and some symbols using bpp = 4
 *https://fonts.google.com/specimen/Montserrat*/
#define LV_FONT_MONTSERRAT_8     0
#define LV_FONT_MONTSERRAT_10    0
#define LV_FONT_MONTSERRAT_12    0
#define LV_FONT_MONTSERRAT_14    1
#define LV_FONT_MONTSERRAT_16    1
#define LV_FONT_MONTSERRAT_18    1
#define LV_FONT_MONTSERRAT_20    1
#define LV_FONT_MONTSERRAT_22    0
#define LV_FONT_MONTSERRAT_24    1
#define LV_FONT_MONTSERRAT_26    0
#define LV_FONT_MONTSERRAT_28    0
#define LV_FONT_MONTSERRAT_30    1
#define LV_FONT_MONTSERRAT_32    0
#define LV_FONT_MONTSERRAT_34    0
#define LV_FONT_MONTSERRAT_36    1
#define LV_FONT_MONTSERRAT_38    0
#define LV_FONT_MONTSERRAT_40    0
#define LV_FONT_MONTSERRAT_42    1
#define LV_FONT_MONTSERRAT_44    0
#define LV_FONT_MONTSERRAT_46    0
#define LV_FONT_MONTSERRAT_48    1
```

I tried my hand at building a firmware from scratch, and sadly it crashes constantly.  So far no issues with your firmware.  Thanks!

**Comment by jdtsmith** [comment]
Update: this is too many fonts, and it was overfilling my application partition.  I trimmed a few out and got it to build and install just fine.

**Comment by russhughes** [comment]
I played with this and was able to make those fonts fit by shrinking the VFS partition and increasing the APP partition.
I have not tested this but it compiles, downloads to my TDisplay and gives me a REPL.   Be sure to erase before flashing any time you change the partition table.

```
# Notes: the offset of the partition table itself is set in
# $IDF_PATH/components/partition_table/Kconfig.projbuild.
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x6000,
phy_init, data, phy,     0xf000,  0x1000,
factory,  app,  factory, 0x10000, 0x280000,
vfs,      data, fat,     0x290000, 0x170000,
```

**Comment by jdtsmith** [comment]
Thanks.  I'm building the newly pulled LV-MPv1.17 with quite a few different fonts, and I managed to trim the app partition to (this is `ports/esp32/partitions.csv`, for posterity):

```
nvs,      data, nvs,     0x9000,  0x6000,
phy_init, data, phy,     0xf000,  0x1000,
factory,  app,  factory, 0x10000, 0x251000,
vfs,      data, fat,     0x261000, 0x19f000,
```

leaving a healthy 1.7MB for filesystem flash on my 4MB device.  The final number is just `0x400000 - vfs_offset`.  It's not too hard to pick your fonts, build it all, and then tweak these numbers to fit the "app" (aka micropython code itself) without much wastage.   

Looks like you got close on a PR for including the driver in the main project.  Testing has been good for me so far; will let you know if I encounter any issues. 

BTW, I've been wondering what overhead MP actually involves (aside from additional memory for LVGL objects)?  I bet it's minimal.  Would be interesting to covert [this demo](https://github.com/lvgl/lv_demos/blob/master/src/lv_demo_benchmark/lv_demo_benchmark.c) to MP and compare.
