### ISSUE TITLE
RuntimeError: st7789 micropython driver requires defining LV_COLOR_DEPTH=16

### ISSUE THREAD

**Issue by jdtsmith** [russhughes/lv_st7789#3]
On my most recent build with MPv1.17 I get a runtime error.  Do you also need to add:

```
make -C ports/esp32 LV_CFLAGS="-DLV_COLOR_DEPTH=16 -DLV_COLOR_16_SWAP=1" 
```

as suggested for the ILI9341 driver?

**Comment by russhughes** [comment]
Yes. It uses the same flush routines as the ILI9341 driver.

**Comment by jdtsmith** [comment]
Thanks, this works.  Not sure why I didn't need it before.  Happy to test the module once it gets included in lv_micropython proper.
