### ISSUE TITLE
Soft reset SPI initialization issue

### ISSUE THREAD

**Issue by jdtsmith** [russhughes/lv_st7789#4]
Once you've initialized this driver, soft resetting leads to 

```
E (58438) spi: spi_bus_initialize(462): SPI bus already initialized.
```  

Is there a way to de-initialize the SPI bus and avoid this?  I've tried `power_down()` but that doesn't do the trick.  Thanks.

**Comment by russhughes** [comment]
Not yet.

**Comment by jdtsmith** [comment]
OK thanks.  I presume this is done in the C code not micropython, so no amount of fussing with machine.SPI would help?

**Comment by russhughes** [comment]
That is my understanding. I believe they are looking at  moving the SPI init into python to solve the issue.
