### ISSUE TITLE
mp_obj_class_lookup

### ISSUE THREAD

**Issue by heixiaoma** [russhughes/lv_st7789#6]
我重新构建后，运行例子出现一下问题，还不知道什么原因
```
assertion "mp_obj_is_dict_or_ordereddict(MP_OBJ_FROM_PTR(type->locals_dict))" failed: file "/home/hxm/Desktop/lv_micropython/py/objtype.c", line 156, function: mp_obj_class_lookup
```

**Comment by heixiaoma** [comment]
After I rebuilt, there was a problem running the example. I don't know why

**Comment by russhughes** [comment]
Does this still happen with the version I updated today?

**Comment by heixiaoma** [comment]
Thanks for the author's support. I'm not next to the computer these two days. When I go back, I'll test my esp32 8MB PSRAM 16MB flash

**Comment by heixiaoma** [comment]
I have no problem using the esp32 s model. There is no problem using the firmware you compiled or compiling by myself. There is a problem when I change to 8MB PSRAM. There may be a problem with my compilation parameters. It is  ESP32 WROVER B

**Comment by heixiaoma** [comment]
Hello, my English is not very good. I don't know if I can express it clearly,

I use https://github.com/lvgl/lv_micropython Compiled firmware

configs
```
from ili9XXX import ili9341, COLOR_MODE_RGB, MADCTL_MY, MADCTL_MX

disp = ili9341(
    mhz=3,
    mosi=18,
    clk=19,
    cs=13,
    dc=12,
    rst=4,
    power=-1,
    backlight=15,
    backlight_on=1,
    width=240,
    height=240,
    colormode=COLOR_MODE_RGB,
    rot=MADCTL_MY | MADCTL_MX)
```
The chip model is esp32-wrover-b 8MB PSRAM / 16MB flash. It is difficult to drive the screen display. The program does not report an error, but the screen does not display a black screen. It will be displayed occasionally, but the displayed results are garbled

**Comment by heixiaoma** [comment]
Thanks to the support of the author, it has been successfully run

**Comment by heixiaoma** [comment]
If I want to reflect the screen through the prism, I need to set the display mode to the mirror mode. At present, it seems that there is no such setting in the parameters. If I need to realize this function, how do I set it?

**Comment by heixiaoma** [comment]
It seems that it can be calculated by colormode itself?

**Comment by heixiaoma** [comment]
rot=57 Mirror mode

**Comment by heixiaoma** [comment]
```
from ili9XXX import st7789
scl=14
sda=13
res=26
dc=27
disp = st7789(
    mosi=sda,
    clk=scl,
    dc=dc,
    rst=res,
    miso=19,
    cs=5,
    power=-1,
    width=240,
    height=240,
    rot=57
    )
```
