### ISSUE TITLE
prebuild .bin seem not work at T-Watch-2020 V3

### ISSUE THREAD

**Issue by gyzhang123** [russhughes/lv_st7789#7]
i burned the prebuild .bin file , however can not connect to micropython .

**Comment by gyzhang123** [comment]
> i burned the prebuild .bin file , however can not connect to micropython .

![图片](https://user-images.githubusercontent.com/24554475/140854229-e37093ef-4be6-4ff1-a40d-c95bc156cdb3.png)

**Comment by russhughes** [comment]
Try setting the burn address to 0x1000 and erase_flash to yes.
