### ISSUE TITLE
Included in lv_micropython?

### ISSUE THREAD

**Issue by jdtsmith** [russhughes/lv_st7789#8]
Did this ever get included in lv_micropython directly?  Seems like the PR was quite close, and otherwise requires re-patching every time there is an update.

**Comment by russhughes** [comment]
No, they wanted changes made to code I didn't write for devices that I didn't have.  I make too many mistakes to trust in code that should work without actually being able to test it.  I may revisit it when I have more time if someone else does not.

**Comment by jdtsmith** [comment]
OK, I've posted over there to see if they want to make those constant generalizing changes themselves, and volunteered to test the result on ST7789; we'll see.  Your code is still working quite well here.  I've found the asyncio timer approach is the most stable.
